[package]
name = "maze"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib","cdylib"]
name = "maze"
path = "src/lib.rs"

[[bin]]
name = "maze-mk"
path = "src/main.rs"
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.8.0"
hex = "0.4.3"
itertools = "0.10.5"
plotters = "0.3.4"
rand_chacha = "0.3.1"
thiserror = "1.0.38"
wasm-bindgen = "0.2.83"

[profile.release]
lto = true

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"]}

[[bench]]
name = "maze_synthesis"
harness = false
