[package]
name = "maze"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = { version = "0.2.8", features = ["js"] }
itertools = "0.10.5"
plotters = "0.3.4"
rand = "0.8.5"
rand_chacha = "0.3.1"
thiserror = "1.0.38"
wasm-bindgen = "0.2.83"

[profile.release]
lto = true
