[toolchain]
channel = "nightly-2025-03-15"
components = [ "rustfmt", "rustc-dev", "rust-analyzer", "rust-src", "rust-std" ]
targets = [ "wasm32-unknown-unknown", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-musl" ]
profile = "minimal"